import { column, Schema, Table } from "@powersync/web";

const text = column.text;
const integer = column.integer;

export const powerSyncTables = [
  "projection_projects",
  "projection_threads",
  "projection_thread_messages",
  "projection_thread_activities",
  "projection_thread_sessions",
  "projection_turns",
  "projection_pending_approvals",
  "projection_state",
  "projection_thread_proposed_plans",
  "client_orchestration_commands",
] as const;

export const t3PowerSyncSchema = new Schema({
  projection_projects: new Table({
    project_id: text,
    title: text,
    workspace_root: text,
    scripts_json: text,
    created_at: text,
    updated_at: text,
    deleted_at: text,
    default_model_selection_json: text,
  }),
  projection_threads: new Table({
    thread_id: text,
    project_id: text,
    title: text,
    branch: text,
    worktree_path: text,
    latest_turn_id: text,
    created_at: text,
    updated_at: text,
    deleted_at: text,
    runtime_mode: text,
    interaction_mode: text,
    model_selection_json: text,
    archived_at: text,
    latest_user_message_at: text,
    pending_approval_count: integer,
    pending_user_input_count: integer,
    has_actionable_proposed_plan: integer,
  }),
  projection_thread_messages: new Table({
    message_id: text,
    thread_id: text,
    turn_id: text,
    role: text,
    text,
    is_streaming: integer,
    created_at: text,
    updated_at: text,
    attachments_json: text,
  }),
  projection_thread_activities: new Table({
    activity_id: text,
    thread_id: text,
    turn_id: text,
    tone: text,
    kind: text,
    summary: text,
    payload_json: text,
    created_at: text,
    sequence: integer,
  }),
  projection_thread_sessions: new Table({
    thread_id: text,
    status: text,
    provider_name: text,
    provider_session_id: text,
    provider_thread_id: text,
    active_turn_id: text,
    last_error: text,
    updated_at: text,
    runtime_mode: text,
    provider_instance_id: text,
  }),
  projection_turns: new Table({
    row_id: integer,
    thread_id: text,
    turn_id: text,
    pending_message_id: text,
    assistant_message_id: text,
    state: text,
    requested_at: text,
    started_at: text,
    completed_at: text,
    checkpoint_turn_count: integer,
    checkpoint_ref: text,
    checkpoint_status: text,
    checkpoint_files_json: text,
    source_proposed_plan_thread_id: text,
    source_proposed_plan_id: text,
  }),
  projection_pending_approvals: new Table({
    request_id: text,
    thread_id: text,
    turn_id: text,
    status: text,
    decision: text,
    created_at: text,
    resolved_at: text,
  }),
  projection_state: new Table({
    projector: text,
    last_applied_sequence: integer,
    updated_at: text,
  }),
  projection_thread_proposed_plans: new Table({
    plan_id: text,
    thread_id: text,
    turn_id: text,
    plan_markdown: text,
    created_at: text,
    updated_at: text,
    implemented_at: text,
    implementation_thread_id: text,
  }),
  client_orchestration_commands: new Table({
    command_id: text,
    session_id: text,
    command_json: text,
    status: text,
    result_sequence: integer,
    error: text,
    created_at: text,
    updated_at: text,
  }),
});
